"""
Time utilities.

All display timestamps are IST (Asia/Kolkata, UTC+5:30),
regardless of the server's system timezone -- GitHub
Actions runners and most cloud VMs (including a fresh
Oracle Cloud instance) default to UTC. Using a fixed
+05:30 offset (rather than relying on system tzdata) means
this is correct everywhere without needing the box's
timezone configured -- IST has no DST, so a fixed offset
is always exactly right.
"""

from datetime import datetime, timezone, timedelta

IST = timezone(timedelta(hours=5, minutes=30))


def now_ist():
    """Current time, timezone-aware, in IST."""
    return datetime.now(timezone.utc).astimezone(IST)


def now_ist_iso():
    """
    Current IST time as an ISO 8601 string with offset,
    e.g. '2026-08-10T15:45:12+05:30'. This is what gets
    stored in the snapshot -- unambiguous and machine
    parseable regardless of what timezone it's later read
    back in.
    """
    return now_ist().isoformat(timespec="seconds")


def format_ist(value):
    """
    Format a stored timestamp for display in Telegram
    messages, e.g. '10 Aug 2026, 03:45 PM IST'.

    Handles:
    - new-style timezone-aware ISO strings (produced by
      now_ist_iso(), going forward)
    - old-style naive ISO strings already sitting in an
      existing snapshot.json from before this fix (those
      were generated by datetime.now() on a UTC server,
      so they're treated as UTC and converted)
    - empty / missing values
    """

    if not value:
        return "-"

    try:
        dt = datetime.fromisoformat(value)
    except (ValueError, TypeError):
        return str(value)

    if dt.tzinfo is None:
        # Legacy naive timestamp from before this fix.
        dt = dt.replace(tzinfo=timezone.utc)

    dt = dt.astimezone(IST)

    return dt.strftime("%d %b %Y, %I:%M %p IST")
